name: CI

on:
  push:
    branches:
      - main # Changez ceci si vous utilisez une autre branche principale
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2

      - name: Installer Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Changez la version si nécessaire

      - name: Installer les dépendances
        run: npm install

      - name: Exécuter les tests
        run: npm test
