name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true" 
          MYSQL_DATABASE: user_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.3.0"

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h 127.0.0.1 --silent; do
            sleep 1
          done

      - name: Create the 'users' table
        run: |
          mysql -h 127.0.0.1 -uroot --password="" user_db < init.sql

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: ""
          DB_NAME: user_db
        run: npm test

      - name: Build Docker image
        run: |
          docker build -t nodejs-simple-app .

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Tag Docker image with workflow version
        run: |
          IMAGE_VERSION="${GITHUB_RUN_NUMBER}" # Or use commit SHA: $(git rev-parse --short HEAD)
          docker tag nodejs-simple-app sofienazzabi/tp1-devops:${IMAGE_VERSION}
          docker push sofienazzabi/tp1-devops:${IMAGE_VERSION}

      - name: Terminate Successfully
        run: echo "All tests completed successfully and Docker image pushed to sofienazzabi/tp1-devops with version tag!"
